# Generated by Django 5.1.3 on 2024-11-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
