# Generated by Django 5.1.3 on 2024-11-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_hash_id'),
        ('user', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='payment.transaction'),
        ),
    ]
