# Generated by Django 5.1.3 on 2024-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='max_common_sentences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
