# Generated by Django 5.1.3 on 2024-11-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plans_max_common_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='max_interview_participations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
