# Generated by Django 5.1.3 on 2024-11-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plans_card_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='transactions',
        ),
    ]
