# Generated by Django 5.1.3 on 2024-11-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_userplan_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='common_sentences_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='daily_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='interview_usage',
            field=models.IntegerField(default=0),
        ),
    ]
