# Generated by Django 5.1.3 on 2024-11-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_userplan_common_sentences_usage_userplan_daily_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
