# Generated by Django 5.1.3 on 2024-11-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('tech', 'Technical'), ('behavior', 'Behavioral')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSubTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interview_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewtheme')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interview_type', models.CharField(choices=[('tech', 'Technical'), ('behavior', 'Behavioral')], max_length=255)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=255)),
                ('answers', models.ManyToManyField(related_name='questions', to='interview.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('tech', 'Technical'), ('behavior', 'Behavioral')], max_length=255)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=255)),
                ('sub_themes', models.ManyToManyField(related_name='interview', to='interview.interviewsubtheme')),
                ('themes', models.ManyToManyField(related_name='interviews', to='interview.interviewtheme')),
                ('questions', models.ManyToManyField(related_name='interviews', to='interview.question')),
            ],
        ),
    ]
