from django.core.management.base import BaseCommand
from sentences.models import Sentences

class Command(BaseCommand):
    def handle(self, *args, **options):

        sentences = [
            "daily standup meeting",
            "backend developer tasks",
            "frontend development issues",
            "fullstack developer workload",
            "test driven development",
            "continuous integration pipeline",
            "continuous deployment process",
            "create a pull request",
            "resolve merge conflicts",
            "deployment pipeline error",
            "fix staging environment",
            "update production environment",
            "apply a hotfix",
            "switch feature branch",
            "submit a bug report",
            "address technical debt",
            "refactor legacy code",
            "write unit tests",
            "run integration tests",
            "perform end-to-end testing",
            "debugging a complex issue",
            "freeze code for deployment",
            "give standup updates",
            "resolve blocker issues",
            "coordinate with scrum master",
            "implement agile methodology",
            "update velocity chart",
            "review burn-down chart",
            "attend retrospective meeting",
            "plan the next sprint",
            "finalize user story",
            "define acceptance criteria",
            "rollback failed deployment",
            "integrate external APIs",
            "build RESTful services",
            "design microservices architecture",
            "run docker containers",
            "manage Kubernetes cluster",
            "fix server downtime issues",
            "handle database migration",
            "commit to version control",
            "clone git repository",
            "use a feature toggle",
            "perform peer programming session",
            "resolve linting errors",
            "optimize application performance",
            "identify memory leaks",
            "address scalability issues",
            "monitor cloud infrastructure",
            "set up CI/CD pipeline",
            "generate access tokens",
            "fix authorization failure",
            "clean up the codebase",
            "update technical documentation",
            "join the on-call rotation",
            "respond to incidents quickly",
            "enable logging and monitoring",
            "review service-level agreements",
            "ensure data persistence",
            "debug client-side rendering",
            "fix server-side rendering",
            "implement state management",
            "connect webhook integrations",
            "handle asynchronous processes",
            "design event-driven architecture",
            "apply dependency injection",
            "use singleton patterns",
            "update the design system",
            "get UI/UX feedback",
            "deliver minimum viable product",
            "test prototype designs",
            "align with stakeholders",
            "finalize OKRs and KPIs",
            "complete a code sprint",
            "work under deadline pressure",
            "reproduce a tricky bug",
            "set branch protection rules",
            "iterate continuous feedback loop",
            "perform load testing",
            "fix browser compatibility issues",
            "address CORS-related problems",
            "handle data serialization tasks",
            "analyze critical path dependencies"
        ]

        for sentence in sentences:
            Sentences.objects.create(sentence=sentence)