# Generated by Django 5.1.3 on 2024-11-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Tech Lead', 'Tech Lead'), ('Developer', 'Developer'), ('Quality Assurance', 'Quality Assurance'), ('Project Manager', 'Project Manager'), ('Product Owner', 'Product Owner'), ('Scrum Master', 'Scrum Master'), ('Designer', 'Designer')], max_length=50)),
                ('is_you', models.BooleanField(default=False)),
                ('voice', models.CharField(blank=True, choices=[('Microsoft Andrew Online (Natural) - English (United States)', 'Microsoft Andrew Online (Natural) - English (United States)'), ('Microsoft Alonso Online (Natural) - Spanish (United States)', 'Microsoft Alonso Online (Natural) - Spanish (United States)'), ('Microsoft Michelle Online (Natural) - English (United States)', 'Microsoft Michelle Online (Natural) - English (United States)'), ('Microsoft Steffan Online (Natural) - English (United States)', 'Microsoft Steffan Online (Natural) - English (United States)'), ('Microsoft Roger Online (Natural) - English (United States)', 'Microsoft Roger Online (Natural) - English (United States)'), ('Microsoft Guy Online (Natural) - English (United States)', 'Microsoft Guy Online (Natural) - English (United States)'), ('Microsoft AvaMultilingual Online (Natural) - English (United States)', 'Microsoft AvaMultilingual Online (Natural) - English (United States)')], max_length=255, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProbablyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('penality', models.TextField(blank=True, null=True)),
                ('who_says_penality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.person')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('is_question', models.BooleanField(default=False)),
                ('is_to_you', models.BooleanField(default=False)),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily.information')),
                ('probably_answers', models.ManyToManyField(blank=True, null=True, to='daily.probablyanswer')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.person')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('your_atributions', models.TextField()),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you', to='daily.person')),
                ('speeches', models.ManyToManyField(to='daily.speech')),
            ],
        ),
    ]
