# Generated by Django 5.1.3 on 2024-11-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_daily_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='people',
            field=models.ManyToManyField(related_name='daily_persons', to='daily.person'),
        ),
    ]
