# Generated by Django 5.1.3 on 2024-11-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan_acquired',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plans'),
        ),
    ]
