# Generated by Django 5.1.3 on 2024-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
